### ISSUE TITLE
Move throttling of database reading.

### ISSUE THREAD

**Issue by PeterAaser** [PeterAaser/SHODAN#1]
Currently throttling of file playback is throttled in the readCSV method in fileIO, this should be done at a much much higher level. Hardcoding it in is acceptable, but in that case it should still be hardcoded at a much higher level, such as in entrypoint.

**Comment by thomaav** [comment]
This is addressed somewhat in 0c062bd3.

A simple test with `cyborg.io.sIO.DB.streamFromDatabase(3).compile.drain.unsafeRunSync()` yields a program runtime of 83 seconds when reading from an input CSV of 91 858 * 1000 samples. With the given sample rate of 20 000, this should amount to ~77 seconds. Running without throttling yields a running time of ~41 seconds, so as long as listeners don't throttle themselves, this seems necessary for a broadcast.

**Comment by PeterAaser** [comment]
Decided to split it into two methods, streamFromDatabase and streamFromDatabaseThrottled.
