### ISSUE TITLE
Investigate using gzip for compression

### ISSUE THREAD

**Issue by PeterAaser** [PeterAaser/SHODAN#4]
The data should be relatively compressible, and fs2 along with fs2-scodec offers compression and decompression. This is not a high priority, but it may be a low hanging fruit worth at least investigating

**Comment by thomaav** [comment]
This is addressed in 947198e1 and f59dd6cd. Simple testing with compression with a simple generated sawtooth wave that plays for ten seconds on 60 channels with a sample rate of 20 000 made the generated file go from 55M to 1.5M. The files are read in at just about the same pace. gzipping actual real data from an MEA reduces file size from 1.2G to 142M. Thus it might be preferable to use `writeCompressed` and `streamCompressed`.

It should likely also be possible to re-inflate compressed data across threads/cores for higher performance (given that compression is moving you from being IO-bound to CPU-bound).
